sudo: required
dist: trusty
language: python
python:
  - "2.7"

# docker-compose is installed by default: https://docs.travis-ci.com/user/docker/#Using-Docker-Compose
before_install:
  - echo "before_install, pwd is `pwd`"
  - echo "before_install, ls -la `ls -la`"
  - sudo apt-get install -y git
  - git clone https://github.com/LukeSwart/docker-shareabouts.git
  - docker pull kartoza/postgis:9.4-2.1
  - cd docker-shareabouts/backend && mv .env.template .env && ./letsdeploy.sh && cd -
  - echo "before_install, docker ps, `docker ps`"
  - echo "before_install, docker logs development_postgis_1, `docker logs development_postgis_1`"

install:
  - echo "install, pwd is `pwd`"
  - echo "install, ls -la `ls -la`"
  - echo "install, docker ps, `docker ps`"
  - echo "install, docker logs development_postgis_1, `docker logs development_postgis_1`"
  - pip install -r requirements.txt

script:
  - src/manage.py test

services:
  - docker
