# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
#
version: 2
jobs:
  build:
    docker:
      - image: smartercleanup/api:release-0.6.5
        environment:
          PASS: pass
          USERNAME: user
          HOST: localhost
          PORT: 25432
      - image: postgres:9.6
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: test_db
    working_directory: /api
    steps:
      - run: "echo 'starting test!!!'"
      - run: "ls -la"
      - checkout
      - run: git log -3
      - run: apt-get install netcat-openbsd
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
            nc -z localhost 25432 && echo Success && exit 0
            echo -n .
            sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Set up DB
          command: |
            ./src/manage.py migrate
      - run:
          command: |
            ./src/manage.py test
